"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";
import Image from "next/image";

const nav = [["O nás","onas"],["Pro zaměstnavatele","zamestnavatele"],["Pro uchazeče","uchazeci"],["Jak spolupráce probíhá","proces"],["FAQ","faq"],["Kariéra","kariera"],["Kontakt","kontakt"]];
const values = [
  ["Spolehlivost","Dodržujeme dohodnuté podmínky a hledáme řešení, na která se naši klienti mohou spolehnout."],
  ["Stabilita","Upřednostňujeme dlouhodobou spolupráci před krátkodobými a nepromyšlenými řešeními."],
  ["Odpovědnost","Každou zakázku řešíme s vědomím odpovědnosti vůči zaměstnavateli i pracovníkům."],
  ["Transparentnost","Komunikujeme otevřeně, srozumitelně a bez skrytých podmínek."],
  ["Respekt","Za každým pracovním místem i životopisem vidíme konkrétního člověka, jeho potřeby, schopnosti a budoucnost."],
  ["Profesionalita","Dbáme na kvalitní výběr pracovníků, pořádek v dokumentaci a průběžnou komunikaci během celé spolupráce."]
];
const employerServices = ["vyhledávání a nábor zaměstnanců","předvýběr vhodných kandidátů","ověření zkušeností, motivace a dostupnosti uchazečů","organizace pracovních pohovorů","nábor jednotlivců i větších pracovních týmů","personální podpora při rozšiřování výroby","pomoc při pokrytí sezónních nebo provozních potřeb","koordinace nástupu vybraných pracovníků","průběžná komunikace se zaměstnanci","podpora při řešení každodenních personálních situací","dlouhodobá péče o spolupráci s klientem"];
const areas = [
 ["Výroba a průmysl",["operátoři výroby","pracovníci montáže","kontrola kvality","obsluha výrobních zařízení","baliči a pomocní pracovníci","pracovníci kovovýroby","pracovníci automobilového průmyslu"]],
 ["Logistika a sklady",["skladníci","pracovníci expedice","picker a packer","řidiči vysokozdvižných vozíků","manipulanti","pracovníci příjmu a výdeje zboží"]],
 ["Technické profese",["údržbáři","montéři","obsluha CNC zařízení"]],
 ["Stavebnictví a řemesla",["pomocní pracovníci","montážní pracovníci"]],
 ["Administrativa a další pozice",["Administrativní, obchodní, úklidové, servisní a další provozní pozice podle požadavků klienta."]]
];
const employerProcess = [
 ["Analýza potřeb","Seznámíme se s vaší společností, provozem, požadovanými profesemi, počtem pracovníků, směnností a termínem nástupu."],
 ["Návrh personálního řešení","Navrhneme vhodný způsob spolupráce, rozsah služeb a konkrétní postup náboru."],
 ["Vyhledání kandidátů","Oslovíme vhodné uchazeče prostřednictvím dostupných náborových kanálů a vlastní databáze kontaktů."],
 ["Předvýběr","Prověříme základní zkušenosti, motivaci, dostupnost, jazykové možnosti a vhodnost uchazeče pro danou pozici."],
 ["Představení kandidátů","Zaměstnavateli představíme vybrané kandidáty odpovídající stanoveným požadavkům."],
 ["Organizace nástupu","Pomůžeme s organizací potřebných kroků tak, aby mohl pracovník nastoupit v dohodnutém termínu."],
 ["Následná péče","Ani po nástupu pracovníka naše práce nekončí. Sledujeme průběh spolupráce a v případě potřeby pomáháme řešit vzniklé situace."]
];
const benefits = [
 ["Individuální řešení","Nevycházíme pouze z názvu pracovní pozice. Zajímá nás prostředí, směnnost, požadované zkušenosti i dlouhodobé cíle zaměstnavatele."],
 ["Rychlá komunikace","Na požadavky klientů reagujeme bez zbytečných prodlev a pravidelně informujeme o průběhu náboru."],
 ["Důkladný výběr kandidátů","Snažíme se předcházet nevhodným nástupům tím, že předem zjišťujeme zkušenosti, možnosti a skutečnou motivaci uchazečů."],
 ["Zkušenost s provozem","Rozumíme specifikům výroby, logistiky, skladů, technických profesí i směnných provozů."],
 ["Dlouhodobé partnerství","Nechceme být pouze dodavatelem kontaktů. Chceme být stabilním partnerem, který pomáhá klientovi řešit personální potřeby dlouhodobě."],
 ["Lidský přístup","Pracovníky nevnímáme jako čísla. Respektujeme jejich důstojnost, zkušenosti a osobní situaci. Právě férový přístup pomáhá budovat stabilnější pracovní týmy."]
];
const applySteps = [
 ["Kontaktujte nás","Zašlete nám svůj životopis nebo základní informace o dosavadní praxi."],
 ["Krátký rozhovor","Probereme vaše zkušenosti, jazykové znalosti, časové možnosti a představu o zaměstnání."],
 ["Výběr vhodné pozice","Pokud máme odpovídající pracovní nabídku, představíme vám její podmínky."],
 ["Pohovor nebo ověření zkušeností","Podle konkrétní pozice může následovat osobní nebo telefonický pohovor, případně praktické ověření dovedností."],
 ["Nástup do zaměstnání","Po odsouhlasení podmínek vám předáme potřebné informace k nástupu."]
];
const faqEmployer = [
 ["Jak rychle dokážete dodat pracovníky?","Termín závisí na typu pozice, počtu pracovníků, požadované kvalifikaci, lokalitě a pracovních podmínkách. Po obdržení konkrétních požadavků připravíme reálný časový odhad."],
 ["Dokážete zajistit větší počet zaměstnanců?","Ano, podle dostupnosti kandidátů a náročnosti jednotlivých pozic můžeme připravit nábor jednotlivců i větších pracovních týmů."],
 ["Prověřujete zkušenosti kandidátů?","Při předvýběru zjišťujeme jejich praxi, motivaci, dostupnost a základní předpoklady pro danou pozici. Rozsah ověření lze přizpůsobit požadavkům klienta."],
 ["Pomáháte také po nástupu pracovníků?","Ano. Průběžná komunikace po nástupu je důležitou součástí stabilní spolupráce."],
 ["Je možné připravit řešení na míru?","Ano. Každému zaměstnavateli připravujeme postup podle jeho konkrétního provozu a personálních potřeb."]
];
const faqCandidate = [
 ["Musím mít životopis?","Životopis je výhodou, ale pokud jej nemáte, můžete nám nejprve poslat základní informace o své praxi, vzdělání a požadované práci."],
 ["Potřebuji umět česky?","Záleží na konkrétní pozici. U některých pracovních míst je nutná základní nebo pokročilá znalost českého jazyka, u jiných není jazyková úroveň hlavní podmínkou."],
 ["Nabízíte ubytování?","Možnost ubytování závisí na konkrétní pracovní nabídce. Pokud je k dispozici, informujeme vás o podmínkách předem."],
 ["Mohu se přihlásit, i když momentálně nemáte vhodnou nabídku?","Ano. Můžete nám zaslat své údaje a po udělení potřebného souhlasu vás budeme moci kontaktovat, pokud se objeví odpovídající pozice."],
 ["Jsou pracovní podmínky sděleny před nástupem?","Ano. Před nástupem uchazeče informujeme o základních podmínkách konkrétní nabídky."]
];

function Container({children,className=""}:{children:ReactNode,className?:string}){return <div className={`container ${className}`}>{children}</div>}
function Button({href,children,variant="gold"}:{href:string,children:ReactNode,variant?:"gold"|"outline"|"dark"}){return <a className={`button button-${variant}`} href={href}>{children}<span aria-hidden="true">→</span></a>}
function Heading({label,title,light=false,intro}:{label:string,title:string,light?:boolean,intro?:string}){return <div className={`section-heading ${light?"light":""}`}><p className="eyebrow">{label}</p><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>}
function CheckList({items}:{items:string[]}){return <ul className="check-list">{items.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul>}

export default function Home(){
 const [scrolled,setScrolled]=useState(false),[faqTab,setFaqTab]=useState<"employer"|"candidate">("employer"),[openFaq,setOpenFaq]=useState(0),[privacy,setPrivacy]=useState(false);
 const [formState,setFormState]=useState<"idle"|"error"|"success">("idle");
 useEffect(()=>{const fn=()=>setScrolled(scrollY>30);addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);if(!String(fd.get("name")||"").trim()||!/^\S+@\S+\.\S+$/.test(String(fd.get("email")||""))||!fd.get("consent")){setFormState("error");return}const contactEmail=process.env.NEXT_PUBLIC_CONTACT_EMAIL||"info@grandmont.cz";const subject=encodeURIComponent(`Zpráva z webu – ${String(fd.get("interest")||"Kontakt")}`);const body=encodeURIComponent(`Jméno: ${fd.get("name")}\nSpolečnost: ${fd.get("company")||"—"}\nTelefon: ${fd.get("phone")||"—"}\nE-mail: ${fd.get("email")}\n\n${fd.get("message")||""}`);window.location.href=`mailto:${contactEmail}?subject=${subject}&body=${body}`;setFormState("success");e.currentTarget.reset()}
 const faqs=faqTab==="employer"?faqEmployer:faqCandidate;
 return <>
 <header className={`site-header ${scrolled?"scrolled":""}`}>
   <a className="brand brand-logo" href="#top" aria-label="GRANDMONT GROUP – úvod"><Image src="/images/grandmont-logo.png" alt="GRANDMONT GROUP s.r.o." width={1254} height={1254} priority/></a>
   <nav className="desktop-nav" aria-label="Hlavní navigace">{nav.map(([l,id])=><a key={id} href={`#${id}`}>{l}</a>)}</nav>
   <Button href="#kontakt" variant="outline">Nezávazná poptávka</Button>
 </header>
 <main>
  <section className="hero" id="top"><div className="hero-content"><p className="eyebrow">Personální a náborová řešení</p><h1>Spolehliví lidé.<br/>Stabilní výkon.<br/><em>Silné partnerství.</em></h1><p className="hero-copy">Pomáháme firmám získávat spolehlivé zaměstnance a uchazečům nacházet stabilní pracovní uplatnění v České republice.</p><div className="hero-actions"><Button href="#zamestnavatele">Hledám zaměstnance</Button><Button href="#uchazeci" variant="outline">Hledám práci</Button></div><ul className="trust-points"><li>✓ Individuální přístup</li><li>✓ Rychlá komunikace</li><li>✓ Dlouhodobá spolupráce</li></ul></div><div className="hero-image" role="img" aria-label="Moderní průmyslový provoz"><div className="image-label"><span>01</span>Lidé, na které je spoleh</div></div></section>

  <section className="trust-section"><Container><div className="trust-intro"><Heading label="Partner pro váš růst" title="Personální řešení s lidským přístupem"/><p>Dodáváme kvalifikované pracovníky a personální řešení, na které se můžete spolehnout. Dlouhodobá partnerství, funkční procesy a výsledky, které posouvají váš byznys vpřed.</p></div><div className="trust-cards">{[["◇","Spolehlivost","Prověření lidé, férový přístup a odpovědnost v každém kroku."],["◷","Rychlost","Reagujeme rychle, dodáváme včas a bez zbytečných průtahů."],["◎","Individuální přístup","Nasloucháme, rozumíme potřebám a tvoříme řešení na míru."]].map(([i,t,d])=><article key={t}><i>{i}</i><h3>{t}</h3><p>{d}</p></article>)}</div></Container></section>
  <section className="service-nav"><Container className="service-grid">{[["01","Nábor zaměstnanců","Kompletní náborový proces od analýzy potřeb po výběr a nástup kandidátů.","zamestnavatele"],["02","Personální řešení","Personální podpora a komplexní outsourcing pracovních sil.","oblasti"],["03","Péče o pracovníky","Podpora, komunikace a řízení, které pomáhá lidem podávat stabilní výkon.","uchazeci"]].map(([n,t,d,id])=><a href={`#${id}`} key={t}><span>{n}</span><h3>{t}</h3><p>{d}</p><b>↗</b></a>)}</Container></section>

  <section className="about section" id="onas"><Container className="split"><div className="about-image image-block" role="img" aria-label="Tým v průmyslovém prostředí"><span>Grandmont / lidé a provoz</span></div><div className="about-copy"><Heading label="O nás" title="Partner, na kterého se můžete spolehnout"/><p className="lead">GRANDMONT GROUP s.r.o. je moderní personální společnost zaměřená na nábor pracovníků, personální podporu a komplexní řešení potřeb zaměstnavatelů.</p><div className="copy-columns"><p>Rozumíme tomu, že za úspěchem každé společnosti stojí především lidé. Proto věnujeme pozornost nejen odborným zkušenostem uchazečů, ale také jejich motivaci, spolehlivosti a schopnosti dlouhodobě se začlenit do pracovního kolektivu.</p><p>Ke každému klientovi přistupujeme individuálně. Nejdříve se důkladně seznámíme s provozem společnosti, požadavky na jednotlivé pozice, pracovním prostředím a očekávaným výsledkem. Následně připravíme řešení odpovídající skutečným potřebám firmy.</p></div><p>Zakládáme si na osobním přístupu, rychlosti, důvěře a otevřené komunikaci. Každou spolupráci vnímáme jako dlouhodobé partnerství, za jehož kvalitu neseme odpovědnost.</p></div></Container></section>
  <section className="mission dark-section"><Container><p className="eyebrow">Naše poslání</p><h2>Spojujeme kvalitní zaměstnavatele se <em>spolehlivými lidmi.</em></h2><div className="mission-grid"><p>Naším posláním je spojovat kvalitní zaměstnavatele se spolehlivými lidmi a vytvářet podmínky pro stabilní, bezpečnou a dlouhodobou spolupráci.</p><p>Pomáháme zaměstnavatelům získat pracovníky, které skutečně potřebují, a zaměstnancům nabízíme férové pracovní příležitosti odpovídající jejich zkušenostem a možnostem.</p></div><blockquote>„Správně vybraný člověk není pouze obsazeným pracovním místem. Je důležitou součástí fungování a dalšího růstu společnosti.“</blockquote></Container></section>
  <section className="values section"><Container><Heading label="Principy spolupráce" title="Naše hodnoty" intro="Principy, na kterých stavíme každou spolupráci."/><div className="values-grid">{values.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></section>
  <section className="visual-story" aria-label="GRANDMONT v obrazech"><figure className="story-photo story-one"><figcaption>Společná strategie</figcaption></figure><figure className="story-photo story-two"><figcaption>Partnerství založené na důvěře</figcaption></figure><figure className="story-photo story-three"><figcaption>Profesionální prostředí</figcaption></figure></section>

  <section className="employers dark-section section" id="zamestnavatele"><Container><div className="employer-intro"><div><Heading label="Pro zaměstnavatele" title="Najdeme pracovníky podle skutečných potřeb vaší společnosti" light/><p>Každý provoz má jiné požadavky. Proto nenabízíme univerzální řešení, ale připravujeme personální podporu podle konkrétní situace klienta.</p><p>Pomůžeme vám definovat požadavky na pracovní pozice, oslovit vhodné kandidáty, provést jejich základní výběr a připravit nástup pracovníků.</p></div><div className="employer-image image-block" role="img" aria-label="Průmyslový pracovník ve výrobní hale"/></div><CheckList items={employerServices}/><div className="legal-note">Rozsah služeb vždy nastavujeme individuálně podle potřeb zaměstnavatele a platných právních podmínek.</div><Button href="#kontakt">Nezávazná poptávka</Button></Container></section>
  <section className="areas section" id="oblasti"><Container><Heading label="Zaměření" title="Oblasti náboru" intro="Pracovníky zajišťujeme pro klíčová odvětví českého trhu."/><div className="areas-grid">{areas.map(([t,arr],i)=><article key={t as string} className={i<2?"featured":""}><span className="area-icon">{["⚙","▦","⌁","⌂","▤"][i]}</span><h3>{t as string}</h3><ul>{(arr as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></Container></section>
  <section className="timeline-section section" id="proces"><Container><Heading label="Proces pro zaměstnavatele" title="Jak probíhá spolupráce" intro="Od prvního požadavku až po následnou péči."/><div className="timeline">{employerProcess.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></Container></section>
  <section className="why dark-section section"><Container><Heading label="Spolupráce" title="Proč spolupracovat s GRANDMONT GROUP" light/><div className="why-grid">{benefits.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></section>
  <section className="employer-cta"><Container className="cta-grid"><div><p className="eyebrow">Personální partner</p><h2>Hledáte zaměstnance?</h2><p>Potřebujete rychle doplnit pracovní tým, obsadit dlouhodobě neobsazené pozice nebo připravujete rozšíření provozu?</p><Button href="#kontakt" variant="dark">Nezávazná poptávka</Button></div><div><h3>Sdělte nám:</h3><CheckList items={["jaké pracovníky hledáte","kolik osob potřebujete","místo výkonu práce","požadovaný termín nástupu","pracovní dobu a směnnost","základní požadavky na uchazeče"]}/><p>Na základě těchto informací vám připravíme individuální návrh spolupráce.</p></div></Container></section>

  <section className="candidates section" id="uchazeci"><Container className="split reverse"><div className="candidate-copy"><Heading label="Pro uchazeče" title="Pomůžeme vám najít stabilní práci"/><p className="lead">Hledáte nové zaměstnání v České republice? Nabízíme pracovní příležitosti ve výrobě, logistice, skladech, technických profesích, stavebnictví a dalších oblastech.</p><p>Při výběru pracovního místa zohledňujeme vaše zkušenosti, kvalifikaci, jazykové znalosti, místo bydliště, možnost dojíždění a preferovaný pracovní režim.</p><p>Před nástupem vám vysvětlíme základní podmínky nabízené pozice, pracovní dobu, místo výkonu práce a požadavky zaměstnavatele.</p><h3>Uchazečům nabízíme</h3><CheckList items={["aktuální nabídky zaměstnání","pomoc s výběrem vhodné pozice","srozumitelné informace o pracovních podmínkách","organizaci pohovoru a nástupu","pomoc s orientací v požadavcích zaměstnavatele","komunikaci před nástupem i během spolupráce","podporu při řešení běžných pracovních situací"]}/></div><div className="candidate-image image-block" role="img" aria-label="Konzultace pracovních podmínek"><span>Práce, která dává smysl</span></div></Container></section>
  <section className="apply section"><Container><Heading label="Jednoduchý postup" title="Jak se ucházet o práci"/><div className="apply-grid">{applySteps.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></section>
  <section className="international"><Container><div className="info-icon">i</div><div><h2>Pro uchazeče ze zahraničí</h2><p>Pomáháme také uchazečům ze zahraničí lépe se orientovat v pracovních příležitostech na českém trhu.</p><p>U každého kandidáta individuálně posuzujeme jeho zkušenosti, jazykové schopnosti, pobytové oprávnění a možnost výkonu konkrétní práce.</p><p className="small">Veškeré kroky musí být prováděny v souladu s platnými právními předpisy České republiky. Nabídka pracovního místa sama o sobě nezaručuje získání nebo prodloužení pobytového či pracovního oprávnění.</p></div></Container></section>

  <section className="faq section" id="faq"><Container><Heading label="Informace" title="Nejčastější otázky"/><div className="faq-tabs" role="tablist"><button role="tab" aria-selected={faqTab==="employer"} onClick={()=>{setFaqTab("employer");setOpenFaq(0)}}>Pro zaměstnavatele</button><button role="tab" aria-selected={faqTab==="candidate"} onClick={()=>{setFaqTab("candidate");setOpenFaq(0)}}>Pro uchazeče</button></div><div className="accordions">{faqs.map(([q,a],i)=><article key={q} className={openFaq===i?"open":""}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{String(i+1).padStart(2,"0")}</span>{q}<i>{openFaq===i?"−":"+"}</i></button><div className="answer"><p>{a}</p></div></article>)}</div></Container></section>
  <section className="career dark-section section" id="kariera"><Container className="career-grid"><div><Heading label="Kariéra" title="Staňte se součástí GRANDMONT GROUP" light/><p>Hledáme schopné, odpovědné a ambiciózní kolegy, kteří chtějí pracovat v oblasti personalistiky, náboru a péče o klienty.</p><p>Pokud vás naše společnost oslovila, pošlete nám krátké představení prostřednictvím jediného kontaktního formuláře níže.</p></div><ol>{["personalisté a náboráři","koordinátoři zaměstnanců","administrativní pracovníci","specialisté na komunikaci se zahraničními uchazeči"].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></Container></section>

  <section className="contact section" id="kontakt"><Container><Heading label="Kontakt" title="Spojte se s námi" intro="Hledáte zaměstnance, nové pracovní uplatnění nebo chcete projednat možnosti spolupráce? Kontaktujte nás."/><div className="contact-grid"><address><h3>GRANDMONT GROUP s.r.o.</h3><dl><div><dt>Sídlo</dt><dd>Na Čečeličce 425/4, Praha 5</dd></div><div><dt>Telefon</dt><dd>[doplnit]</dd></div><div><dt>E-mail</dt><dd><a href="mailto:info@grandmont.cz">info@grandmont.cz</a></dd></div><div><dt>Web</dt><dd>[doplnit]</dd></div><div><dt>IČO</dt><dd>[doplnit]</dd></div><div><dt>Pro zaměstnavatele</dt><dd>[doplnit kontakt]</dd></div><div><dt>Pro uchazeče</dt><dd>[doplnit kontakt]</dd></div></dl></address><form noValidate onSubmit={submit}><div className="form-grid"><label>Jméno a příjmení *<input name="name" autoComplete="name" required/></label><label>Společnost<input name="company" autoComplete="organization"/></label><label>Telefon<input name="phone" type="tel" autoComplete="tel"/></label><label>E-mail *<input name="email" type="email" autoComplete="email" required/></label></div><label>Mám zájem o<select name="interest" defaultValue="Zaměstnance"><option>Zaměstnance</option><option>Práci</option><option>Spolupráci</option></select></label><label>Vaše zpráva<textarea name="message" rows={4}/></label><label className="consent"><input name="consent" type="checkbox" required/><span>Souhlasím se zpracováním osobních údajů.</span></label>{formState==="error"&&<p className="form-message error" role="alert">Vyplňte prosím jméno, platný e-mail a potvrďte souhlas.</p>}{formState==="success"&&<p className="form-message success" role="status">Zpráva je připravena k odeslání e-mailem.</p>}<button className="button button-gold" type="submit">Odeslat e-mail <span>→</span></button><p className="form-legal">Odesláním formuláře potvrzujete, že jste se seznámili se zásadami zpracování osobních údajů.</p></form></div></Container></section>
  <section className="final-cta"><Container><p className="eyebrow">GRANDMONT GROUP s.r.o.</p><h2>Budujme úspěch společně</h2><p>Ať už hledáte spolehlivé zaměstnance, stabilní pracovní příležitost nebo dlouhodobého personálního partnera, jsme připraveni projednat vaše potřeby a najít odpovídající řešení.</p><strong>Síla v lidech. Stabilita v partnerství. Cesta k růstu.</strong><Button href="#kontakt">Kontaktujte nás</Button></Container></section>
 </main>
 <footer><Container><div className="footer-top"><a className="brand brand-logo footer-logo" href="#top"><Image src="/images/grandmont-logo.png" alt="GRANDMONT GROUP s.r.o." width={1254} height={1254}/></a><p>Spolehliví lidé. Stabilní výkon.<br/>Silné partnerství.</p><nav>{nav.filter((_,i)=>[0,1,2,5,6].includes(i)).map(([l,id])=><a key={id} href={`#${id}`}>{l}</a>)}</nav></div><div className="footer-bottom"><span>© GRANDMONT GROUP s.r.o.</span><div><button onClick={()=>setPrivacy(true)}>Ochrana osobních údajů</button><a href="#kontakt">Cookies</a><a href="#top" aria-label="Zpět nahoru">↑ Nahoru</a></div></div></Container></footer>
 {privacy&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setPrivacy(false)}><section className="privacy-modal" role="dialog" aria-modal="true" aria-labelledby="privacy-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setPrivacy(false)} aria-label="Zavřít">×</button><p className="eyebrow">Právní informace</p><h2 id="privacy-title">Ochrana osobních údajů</h2><p>Osobní údaje uchazečů a obchodních partnerů zpracováváme pouze v nezbytném rozsahu, za stanoveným účelem a v souladu s platnými právními předpisy.</p><p>Podrobné informace o zpracování osobních údajů, době jejich uchování a právech subjektů údajů budou uvedeny v samostatných zásadách ochrany osobních údajů.</p></section></div>}
 </>
}
